version: '3.5'
services:
  kanban-backend:
    build:
      context: .
      args:
        - COOKIE_SECRET=${COOKIE_SECRET}
        - FRONTEND_URL=${FRONTEND_URL}
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgresdb
    command: ['npm', 'run', 'dev']

  postgresdb:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
