version: '3'
services:
  kanban-backend:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
